# WARNING
# COPY THIS FILE OUT LOCALLY FIRST, IT MAY HAVE CHANGED
---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - USER=transmission
      - PASS=transmission
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
      - 9091:9091
    volumes:
      - $VOLUMEDIR/transmission:/config
      - "/media/pit/media/downloads:/downloads"
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: sinkhole
    environment:
      PUID: 1000
      PGID: 1004
      TZ: Europe/London
    volumes:
      - $VOLUMEDIR/syncthing/config:/config
      - $VOLUMEDIR/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
  repobackup:
    image: dan1elhughes/repobackup
    container_name: repobackup
    restart: unless-stopped
    volumes:
      - $VOLUMEDIR/repobackup:/mirror
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - $VOLUMEDIR/mysql:/var/lib/mysql
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    restart: unless-stopped
    hostname: motioneye
    ports:
      - 8765:8765
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/motioneye/etc:/etc/motioneye
      - $VOLUMEDIR/motioneye/varlib:/var/lib/motioneye
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $VOLUMEDIR/plex:/config
      - "/media/pit/media/media:/media"
    restart: unless-stopped
  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - $VOLUMEDIR/freshrss:/config
    ports:
      - 8434:80
    restart: unless-stopped
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - mysql
    restart: unless-stopped
  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    restart: unless-stopped
    environment:
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_ADMIN_PASSWORD=admin
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_SERVER=mysql
      - PHOTOPRISM_DATABASE_USER=root
      - PHOTOPRISM_DATABASE_PASSWORD=root
      - UID=1000
      - GID=1003
    ports:
      - "2342:2342"
    volumes:
      - "$VOLUMEDIR/photoprism:/photoprism/originals"
  redis:
    container_name: redis
    image: redis:6.0
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "$VOLUMEDIR/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  paperlessng:
    container_name: paperless
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - 8774:8000
    volumes:
      - "$VOLUMEDIR/paperless/data:/usr/src/paperless/data"
      - "$VOLUMEDIR/paperless/media:/usr/src/paperless/media"
      - "$VOLUMEDIR/paperless/export:/usr/src/paperless/export"
      - "$VOLUMEDIR/paperless/consume:/usr/src/paperless/consume"
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBUSER: postgres
      PAPERLESS_DBPASS: postgres
      USERMAP_UID: 1000
      USERMAP_GID: 1004
      PAPERLESS_ADMIN_USER: paperless
      PAPERLESS_ADMIN_PASSWORD: paperless
      PAPERLESS_AUTO_LOGIN_USERNAME: paperless
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/homeassistant:/config"
      - "/$VOLUMEDIR/homeassistant-media:/media"
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports:
      - 8123:8123 #optional
  eclipse-mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "/home/dan/sinkhole/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "$VOLUMEDIR/mosquitto/data:/mosquitto/data"
      - "$VOLUMEDIR/mosquitto/log:/mosquitto/log"
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/jackett:/config"
    ports:
      - 9117:9117
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/sonarr/config:/config"
      - "/media/pit/media:/data"
      - "/media/pit/media/downloads:/downloads"
    ports:
      - 8989:8989
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/radarr/config:/config"
      - "/media/pit/media:/data"
      - "/media/pit/media/downloads:/downloads"
    ports:
      - 7878:7878
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/lidarr/config:/config"
      - "/media/pit/media:/data"
      - "/media/pit/media/downloads:/downloads"
    ports:
      - 8686:8686
  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    environment:
      TZ: Europe/London
    ports:
      - 4040:4040
      - 4041:4041
    user: 1000:1004
    volumes:
      - "/media/pit/media/media/playlists:/var/playlists"
      - "/media/pit/media/media/podcasts:/var/podcasts"
      - "/$VOLUMEDIR/airsonic:/var/airsonic"
      - "/media/pit/media/media/music:/var/music"
