# WARNING
# COPY THIS FILE OUT LOCALLY FIRST, IT MAY HAVE CHANGED
---
version: "2"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - $VOLUMEDIR/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "0:0" # ¯\_(ツ)_/¯
    ports:
      - 3000:3000
    volumes:
      - $VOLUMEDIR/grafana:/var/lib/grafana
  organizr:
    image: organizr/organizr
    container_name: organizr
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - $VOLUMEDIR/organizr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
      - 9091:9091
    volumes:
      - $VOLUMEDIR/transmission:/config
      - /media/pit/torrents/watch:/watch
      - /media/pit/torrents/downloads:/downloads
  sync:
    image: resilio/sync
    container_name: sync
    restart: unless-stopped
    ports:
      - 55555
    volumes:
      - $VOLUMEDIR/sync:/mnt/sync
    environment:
      PUID: 1000
      PGID: 1004
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: sinkhole
    environment:
      PUID: 1000
      PGID: 1004
      TZ: Europe/London
    volumes:
      - $VOLUMEDIR/sync/config:/config
      - $VOLUMEDIR/sync/data:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
  repobackup:
    image: dan1elhughes/repobackup
    container_name: repobackup
    restart: unless-stopped
    volumes:
      - $VOLUMEDIR/repobackup:/mirror
  piholeinflux:
    image: registry.gitlab.com/janw/pi-hole-influx
    container_name: pihole-exporter
    restart: unless-stopped
    environment:
      PIHOLE_INFLUXDB_HOST: influxdb
      PIHOLE_INFLUXDB_PORT: "8086"
      PIHOLE_INFLUXDB_USERNAME: "root"
      PIHOLE_INFLUXDB_PASSWORD: "root"
      PIHOLE_INFLUXDB_DATABASE: "telegraf"
      PIHOLE_INSTANCES: "sinkhole=http://192.168.1.128/admin/api.php"
    depends_on:
      - influxdb
  lychee:
    container_name: lychee
    image: linuxserver/lychee
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - $VOLUMEDIR/lychee:/config
      - /home/dan/lychee:/pictures
    ports:
      - 8111:80
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - $VOLUMEDIR/mysql:/var/lib/mysql
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    restart: unless-stopped
    hostname: motioneye
    ports:
      - 8765:8765
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $VOLUMEDIR/motioneye/etc:/etc/motioneye
      - $VOLUMEDIR/motioneye/varlib:/var/lib/motioneye
  timemachine:
    container_name: timemachine
    restart: unless-stopped
    volumes:
      - /media/pit/timemachine:/timemachine
    ports:
      - 548:548
      - 636:636
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    image: odarriba/timemachine
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $VOLUMEDIR/plex:/config
      - "/media/pit/media/TV Shows:/tv"
      - /media/pit/media/Movies:/movies
    restart: unless-stopped
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - $VOLUMEDIR/freshrss:/config
    ports:
      - 8123:80
    restart: unless-stopped
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - mysql
    restart: unless-stopped
