---
version: "2"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - $VOLUMEDIR/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "0:0" # ¯\_(ツ)_/¯
    ports:
      - 3000:3000
    volumes:
      - $VOLUMEDIR/grafana:/var/lib/grafana
  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - $VOLUMEDIR/organizr:/config
  urbackup:
    image: uroni/urbackup-server
    container_name: urbackup
    restart: unless-stopped
    volumes:
      - $VOLUMEDIR/urbackup-db:/var/urbackup
      - $VOLUMEDIR/urbackup-backups:/backups
    network_mode: "host"
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
      - 9091:9091
    volumes:
      - $VOLUMEDIR/transmission:/config
      - /media/pit/shares/torrents/watch:/watch
      - /media/pit/shares/torrents/downloads:/downloads
  sync:
    image: resilio/sync
    container_name: sync
    restart: unless-stopped
    ports:
      - 55555
    volumes:
      - $VOLUMEDIR/sync:/mnt/sync
  repobackup:
    image: dan1elhughes/repobackup
    container_name: repobackup
    restart: unless-stopped
    volumes:
      - $VOLUMEDIR/repobackup:/mirror
  piholeinflux:
    image: registry.gitlab.com/janw/pi-hole-influx
    container_name: pihole-exporter
    restart: unless-stopped
    environment:
      PIHOLE_INFLUXDB_HOST: influxdb
      PIHOLE_INFLUXDB_PORT: "8086"
      PIHOLE_INFLUXDB_USERNAME: "root"
      PIHOLE_INFLUXDB_PASSWORD: "root"
      PIHOLE_INFLUXDB_DATABASE: "telegraf"
      PIHOLE_INSTANCES: "sinkhole=http://192.168.1.128/admin/api.php"
  iot-gateway:
    container_name: iot-gateway
    image: mozillaiot/gateway:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - $VOLUMEDIR/iot-gateway:/home/node/.mozilla-iot
