# WARNING
# COPY THIS FILE OUT LOCALLY FIRST, IT MAY HAVE CHANGED
---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - USER=transmission
      - PASS=transmission
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
      - 9092:9091
    volumes:
      - $VOLUMEDIR/transmission:/config
      - "/media/pit/media/downloads:/downloads"
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $VOLUMEDIR/plex:/config
      - "/media/pit/media/media:/media"
    restart: unless-stopped
  spis:
    container_name: spis
    image: ghcr.io/gbbirkisson/spis:latest
    restart: unless-stopped
    ports:
      - '2342:8080'
    volumes:
        - '$VOLUMEDIR/spis/media:/var/lib/spis/media'
        - '$VOLUMEDIR/spis/data:/var/lib/spis/data'
  redis:
    container_name: redis
    image: redis:6.0
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "$VOLUMEDIR/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  paperlessng:
    container_name: paperless
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - 8774:8000
    volumes:
      - "$VOLUMEDIR/paperless/data:/usr/src/paperless/data"
      - "$VOLUMEDIR/paperless/media:/usr/src/paperless/media"
      - "$VOLUMEDIR/paperless/export:/usr/src/paperless/export"
      - "$VOLUMEDIR/paperless/consume:/usr/src/paperless/consume"
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBUSER: postgres
      PAPERLESS_DBPASS: postgres
      USERMAP_UID: 1000
      USERMAP_GID: 1004
      PAPERLESS_ADMIN_USER: paperless
      PAPERLESS_ADMIN_PASSWORD: paperless
      PAPERLESS_AUTO_LOGIN_USERNAME: paperless
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/sonarr/config:/config"
      - "/media/pit/media:/data"
      - "/media/pit/media/downloads:/downloads"
    ports:
      - 8989:8989
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/radarr/config:/config"
      - "/media/pit/media:/data"
      - "/media/pit/media/downloads:/downloads"
    ports:
      - 7878:7878
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/lidarr/config:/config"
      - "/media/pit/media:/data"
      - "/media/pit/media/downloads:/downloads"
    ports:
      - 8686:8686
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "/$VOLUMEDIR/prowlarr:/config"
    ports:
      - 9696:9696
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: on-failure
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
        WATCHTOWER_NOTIFICATION_URL: "$WATCHTOWER_NOTIFICATION_URL"
        WATCHTOWER_RUN_ONCE: "true"
        WATCHTOWER_NOTIFICATION_TITLE_TAG: sinkhole
  ombi:
    container_name: ombi
    image: lscr.io/linuxserver/ombi:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=Europe/London
    volumes:
      - "${VOLUMEDIR?error}/ombi:/config"
    ports:
      - 3579:3579
