---
services:

  redis:
    container_name: redis
    image: redis:6.0
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "$VOLUMEDIR/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  paperlessng:
    container_name: paperless
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - 8774:8000
    volumes:
      - "$VOLUMEDIR/paperless/data:/usr/src/paperless/data"
      - "$VOLUMEDIR/paperless/media:/usr/src/paperless/media"
      - "$VOLUMEDIR/paperless/export:/usr/src/paperless/export"
      - "$VOLUMEDIR/paperless/consume:/usr/src/paperless/consume"
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBUSER: postgres
      PAPERLESS_DBPASS: postgres
      USERMAP_UID: 1000
      USERMAP_GID: 1004
      PAPERLESS_ADMIN_USER: paperless
      PAPERLESS_ADMIN_PASSWORD: paperless
      PAPERLESS_AUTO_LOGIN_USERNAME: paperless
