# WARNING
# COPY THIS FILE OUT LOCALLY FIRST, IT MAY HAVE CHANGED
---
services:

  # TODO: Move this
  # spis:
  #   container_name: spis
  #   image: ghcr.io/gbbirkisson/spis:latest
  #   restart: unless-stopped
  #   ports:
  #     - '2342:8080'
  #   volumes:
  #       - '$VOLUMEDIR/spis/media:/var/lib/spis/media'
  #       - '$VOLUMEDIR/spis/data:/var/lib/spis/data'

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
        WATCHTOWER_SCHEDULE: "@monthly"
        WATCHTOWER_NOTIFICATION_URL: "$WATCHTOWER_NOTIFICATION_URL"
        WATCHTOWER_CLEANUP: "true"
        WATCHTOWER_DEBUG: "true"
        WATCHTOWER_NOTIFICATION_TITLE_TAG: "${HOST?error}"
